# ArgoCD App: Sync Sigstore ClusterImagePolicy resources.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/ptduong04/temp.git
    path: policies
    targetRevision: main
    directory:
      exclude: tests/*
  destination:
    server: https://kubernetes.default.svc
    namespace: cosign-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
    - ServerSideApply=true
    - SkipDryRunOnMissingResource=true
